version: '3.8'

services:
  wordpress:
    build:
      context: .
      dockerfile: docker/wordpress/Dockerfile
    container_name: bedrock_wordpress
    volumes:
      - ./bedrock:/var/www/html
      - ./bedrock/web/app/uploads:/var/www/html/web/app/uploads
    working_dir: /var/www/html
    depends_on:
      - mysql
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=bedrock_db
    restart: always

  nginx:
    image: nginx:latest
    container_name: bedrock_nginx
    volumes:
      - ./bedrock:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "89:80"
    depends_on:
      - wordpress

  mysql:
    image: mysql:8.0
    container_name: bedrock_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bedrock_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

